replicaCount: 2

containerName: authenticate-service
containerPort: 3000

image:
  repository: harunaga113/authenticate-service
  tag: dev1.0.0

metadata:
  name: authenticate-service
  labels:
    app: authenticate-service

resources:
  limits:
    cpu: 500m
    memory: 128Mi

service:
  name: authenticate-service
  type: ClusterIP
  port: 9000
  targetPort: 3000

ingress:
  path: /auth
  pathType: Prefix
