replicaCount: 3

containerName: k8s-web-to-nginx
containerPort: 3000

image:
  repository: harunaga113/k8s-web-to-nginx
  tag: "1.0.0"

metadata:
  name: k8s-web-to-nginx
  labels:
    app: k8s-web-to-nginx

resources:
  limits:
    cpu: 500m
    memory: 128Mi

service:
  type: ClusterIP
  port: 3333
  targetPort: 3000
