apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.metadata.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}